#ifndef LIBNDSL_CONFIG_HPP_
#define LIBNDSL_CONFIG_HPP_

// default to 1MB
#define LIBNDSL_COROUTINE_STACK_SIZE (1024 * 1024) /*byte*/

#define LIBNDSL_FRAMEWORK_MAX_EVENT_PER_LOOP (128)

#define LIBNDSL_NET_BACKLOG (16)
#define LIBNDSL_NET_REQUEST_SIZE_THRESHOLD (128 * 1024)
#define LIBNDSL_NET_MAX_IOV (128)

#endif